// timezones.ts
export const TIMEZONES = [
  { label: "(UTC −12:00) Baker Island", value: "Etc/GMT+12" },
  { label: "(UTC −11:00) Niue", value: "Pacific/Niue" },
  { label: "(UTC −10:00) Hawaii", value: "Pacific/Honolulu" },
  { label: "(UTC −09:00) Alaska", value: "America/Anchorage" },
  { label: "(UTC −08:00) Pacific Time (US & Canada)", value: "America/Los_Angeles" },
  { label: "(UTC −07:00) Mountain Time (US & Canada)", value: "America/Denver" },
  { label: "(UTC −06:00) Central Time (US & Canada)", value: "America/Chicago" },
  { label: "(UTC −05:00) Eastern Time (US & Canada)", value: "America/New_York" },
  { label: "(UTC −04:00) Atlantic Time", value: "America/Halifax" },
  { label: "(UTC −03:30) Newfoundland", value: "America/St_Johns" },
  { label: "(UTC −03:00) Buenos Aires", value: "America/Argentina/Buenos_Aires" },
  { label: "(UTC −02:00) South Georgia", value: "Atlantic/South_Georgia" },
  { label: "(UTC −01:00) Azores", value: "Atlantic/Azores" },
  { label: "(UTC ±00:00) UTC / GMT", value: "UTC" },
  { label: "(UTC +01:00) Central European Time", value: "Europe/Berlin" },
  { label: "(UTC +02:00) Eastern European Time", value: "Europe/Athens" },
  { label: "(UTC +03:00) Moscow", value: "Europe/Moscow" },
  { label: "(UTC +03:30) Tehran", value: "Asia/Tehran" },
  { label: "(UTC +04:00) Dubai", value: "Asia/Dubai" },
  { label: "(UTC +04:30) Kabul", value: "Asia/Kabul" },
  { label: "(UTC +05:00) Pakistan Standard Time", value: "Asia/Karachi" },
  { label: "(UTC +05:30) India Standard Time", value: "Asia/Kolkata" },
  { label: "(UTC +05:45) Nepal", value: "Asia/Kathmandu" },
  { label: "(UTC +06:00) Bangladesh", value: "Asia/Dhaka" },
  { label: "(UTC +06:30) Myanmar", value: "Asia/Yangon" },
  { label: "(UTC +07:00) Thailand", value: "Asia/Bangkok" },
  { label: "(UTC +08:00) China / Singapore", value: "Asia/Shanghai" },
  { label: "(UTC +09:00) Japan", value: "Asia/Tokyo" },
  { label: "(UTC +09:30) Australia (Central)", value: "Australia/Adelaide" },
  { label: "(UTC +10:00) Australia (Eastern)", value: "Australia/Sydney" },
  { label: "(UTC +11:00) Solomon Islands", value: "Pacific/Guadalcanal" },
  { label: "(UTC +12:00) New Zealand", value: "Pacific/Auckland" },
  { label: "(UTC +13:00) Tonga", value: "Pacific/Tongatapu" },
  { label: "(UTC +14:00) Line Islands", value: "Pacific/Kiritimati" },
];
